hl.on("hyprland.start", function()
	-- hl.exec_cmd("/nix/store/5gln2rkcjx93cr5x0rr3wqrxjdmshd2f-dbus-1.16.2/bin/dbus-update-activation-environment --systemd --all && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target")
	-- hl.exec_cmd("wl-paste --type text --watch cliphist store")
	-- hl.exec_cmd("wl-paste --type image --watch cliphist store")
	-- hl.exec_cmd("dbus-update-activation-environment --all --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	-- hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	-- hl.exec_cmd("systemctl --user start hyprpolkitagent.service")
	-- hl.exec_cmd("qs -c overview")
	-- hl.exec_cmd("killall -q awww;sleep .5 && awww-daemon")
	-- hl.exec_cmd("killall -q waybar;sleep .5 && waybar")
	-- hl.exec_cmd("killall -q swaync;sleep .5 && swaync")
	-- hl.exec_cmd("nm-applet --indicator")
	-- hl.exec_cmd("sh -lc 'sleep 2 && (qs-wallpapers-restore || waypaper --wallpaper /nix/store/a1mp2kac9jwwgf3n025qqbfcys4vpc70-mountainscapedark.jpg --backend awww) >/dev/null 2>&1 || true'")
end)
